### ISSUE TITLE
[FEATURE] BackfillRequest

### ISSUE THREAD

**Issue by george-zubrienko** [SneaksAndData/arcane-operator#139]
### Description

Using annotation to do a backfill turned out to be slightly cumbersome. Here are a few issues we have to manually tackle:
- Rows per group for backfills needs to be much higher to speed up loading
- Backfill with MERGE behaviour is only possible as a lookback, but we cannot specify a custom date range to "fill the missing holes" in data
- Backfill must perform a lookback on completion, for the duration of the backfill itself + some buffer, to avoid dataloss after streaming container starts
- There is little control of a *timestamp* the backfill starts from. While this is not critical for many plugins, for Synapse this is crucial due to lack of snapshot table that can be used as a baseline

### Possible solution

See below

**Comment by s-vitaliy** [comment]
Add a custom resource definition that defines the `BackfillRequest` custom resource with two fields:

```yaml
apiVersion: arcane.sneaksanddata.com/v1alpha1
kind: BackfillRequest
metadata:
  namespace: arcane
  name: example-backfill-1
spec:
  streamClass: MyStream
  streamId: "stream-123"
  streamContextOverrides:
    param1: "value1"
    param2: "value2"
  stopWhenCompleted: true
  reason: A human-readable comment
  initiator: Initiator name in human-readable format
  completed: false
status:
    jobStatus: Running
```

- [ ] When the BackfillRequest object is created, Arcane creates a backfill job that runs until completion.
- [ ] If the backfill request is modified, the backfill restarts with the new settingsnt
- [ ] If the backfill request is deleted, the backfill process should be interrupted.
- [ ] When the backfill process is completed, Arcane operator sets the `completed` field to `true`.
- [ ] Changing the completed field from `true` to `false` is not allowed (forced by validation controller).
- [ ] Arcane Operator uses `streamContextOverrides` field to provider `STREAMCONTEXT_OVERRIDE` environment variable to the backfill job.
- [ ] Arcane Streaming plugin merges  `STREAMCONTEXT_SPEC`  and `STREAMCONTEXT_OVERRIDE` to build the actual StreamContext value.
- [ ] The completed backfill requests stays in the cluster for history.
- [ ] Arcane Operator manages the maximum number of backfill requests and deletes the old requests.
